# vim: set shiftwidth=2 tabstop=2 softtabstop=-1 expandtab:
---
- name: Keeper Set
  hosts: "my_systems"
  gather_facts: no

  tasks:
  - name: "Get Current Password"
    keepersecurity.keeper_secrets_manager.keeper_get:
      uid: "{{ uid }}"
      field: "Password"
    register: "my_password"

  - name: "Print Password"
    debug:
      msg: "Current Password {{ my_password.value }}"
      verbosity: 0

  - name: "Set Password Value"
    keepersecurity.keeper_secrets_manager.keeper_set:
      uid: "{{ uid }}"
      field: "password"
      value: "{{ new_password }}"

  # It's mocked, we don't update our test data :/
