- hosts: localhost
  collections:
    - keepersecurity.keeper_secrets_manager
  tasks:
    - name: Get secret
      keeper_secrets_manager_core:
        keeper_config: "{{ keeper_config_base64 }}"
        records:
          - uid: "{{ record_uid }}"