---
- name: Test KSM v1.3.0 Notes Feature (PR #927)
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - keepersecurity.keeper_secrets_manager

  vars:
    shared_folder_uid: "bRPjVkhKvEjL95Lp-ForNA"
    initial_notes: "Initial notes created by AAP test"
    updated_notes: "Updated notes via keeper_set - PR #927 test"

  tasks:
    # Step 1: Create a new record with notes
    - name: "Step 1 - Create test record with notes"
      keeper_create:
        shared_folder_uid: "{{ shared_folder_uid }}"
        record_type: login
        title: "PR927 Test Record - {{ now(fmt='%Y%m%d_%H%M%S') }}"
        login: "test_user"
        password: "test_password_123"
        notes: "{{ initial_notes }}"
      register: created_record

    - name: "Display created record UID"
      ansible.builtin.debug:
        msg: "Created record UID: {{ created_record.uid }}"

    # Step 2: Read notes from the created record (KSM-768)
    - name: "Step 2 - Read notes from record (KSM-768)"
      keeper_get:
        uid: "{{ created_record.uid }}"
        notes: yes
      register: notes_read

    - name: "Display read notes"
      ansible.builtin.debug:
        msg: "Notes read: {{ notes_read.value }}"

    - name: "Verify initial notes match"
      ansible.builtin.assert:
        that:
          - notes_read.value == initial_notes
        fail_msg: "Notes read do not match initial notes!"
        success_msg: "KSM-768 PASS: Notes read successfully"

    # Step 3: Update notes using keeper_set (KSM-714)
    - name: "Step 3 - Update notes using keeper_set (KSM-714)"
      keeper_set:
        uid: "{{ created_record.uid }}"
        field_type: notes
        value: "{{ updated_notes }}"
      register: notes_set

    - name: "Display set result"
      ansible.builtin.debug:
        var: notes_set

    # Step 4: Verify notes were updated
    - name: "Step 4 - Read notes again to verify update"
      keeper_get:
        uid: "{{ created_record.uid }}"
        notes: yes
      register: notes_verify

    - name: "Verify updated notes match"
      ansible.builtin.assert:
        that:
          - notes_verify.value == updated_notes
        fail_msg: "Updated notes do not match!"
        success_msg: "KSM-714 PASS: Notes updated successfully"

    # Summary
    - name: "Test Summary"
      ansible.builtin.debug:
        msg:
          - "=========================================="
          - "PR #927 Test Results - Notes Feature"
          - "=========================================="
          - "Record UID: {{ created_record.uid }}"
          - "KSM-768 (Read Notes):  PASS"
          - "KSM-714 (Write Notes): PASS"
          - "=========================================="
