---
- name: Test with Full Module Path
  hosts: 127.0.0.1
  connection: local
  gather_facts: false

  tasks:
    - name: Test keeper_info with full path
      keepersecurity.keeper_secrets_manager.keeper_info:
      register: info_result
      failed_when: false

    - name: Show info result
      debug:
        var: info_result

    - name: Test keeper_get with full path
      keepersecurity.keeper_secrets_manager.keeper_get:
        uid: "test-uid-should-fail-but-module-should-be-found"
      register: get_result
      failed_when: false

    - name: Show get result
      debug:
        var: get_result

    - name: Success message
      debug:
        msg:
          - "✅ Collection is working with full module paths!"
          - "Modules are being found and loaded properly"
      when: info_result is defined or get_result is defined