---
- name: Test Keeper Secrets Manager
  hosts: localhost
  connection: local
  gather_facts: false

  collections:
    - keepersecurity.keeper_secrets_manager

  tasks:
    - name: Retrieve a secret from Keeper
      keeper_get:
        uid: "iGEYalKPyahj7BJyJDFSIw"
        field: login
      register: ksm_secret

    - name: Display retrieved value
      ansible.builtin.debug:
        msg: "Successfully retrieved login: {{ ksm_secret.value }}"
